"""Update users table

Revision ID: 1a427112f21a
Revises: cc5cc15ea2e5
Create Date: 2021-01-27 17:30:53.433714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a427112f21a"
down_revision = "cc5cc15ea2e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
