"""create chatroom table

Revision ID: 27d51c99eadc
Revises: 8a42f011bbd2
Create Date: 2021-01-26 10:49:13.427724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27d51c99eadc"
down_revision = "8a42f011bbd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatrooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatrooms_id"), "chatrooms", ["id"], unique=False)
    op.create_table(
        "chatroom_users",
        sa.Column("chatroom_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["chatroom_id"], ["chatrooms.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    )
    op.add_column("users", sa.Column("image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image")
    op.drop_table("chatroom_users")
    op.drop_index(op.f("ix_chatrooms_id"), table_name="chatrooms")
    op.drop_table("chatrooms")
    # ### end Alembic commands ###
