"""update messages table

Revision ID: 8a42f011bbd2
Revises: 616da90da43b
Create Date: 2021-01-26 10:23:17.318880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a42f011bbd2"
down_revision = "616da90da43b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_messages_type"), "messages", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_type"), table_name="messages")
    # ### end Alembic commands ###
